### ISSUE TITLE
Feature request: FTP fetch from dev_usb000

### ISSUE THREAD

**Issue by jimbob4000** [Roet-Ivar/Webman-Classics-Maker#20]
Would be great to be able to fetch from dev_usb000

**Comment by Roet-Ivar** [comment]
Good suggestion for a future release!

NOTE TO SELF:
In order to have separate paths working the implementation of the  gamelist needs to be redesigned to use of unique entries by filepath (folderpath + filename), today it uses filename which won't work with duplicates. These names are shown directly in the list and used as a callback.

**Comment by Roet-Ivar** [comment]
@jimbob4000 this feature is now live
